version: '3.8'

services:
  mongo_db:
    image: mongo
    container_name: "mongo_db"
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=marvel
      - MONGO_INITDB_ROOT_USERNAME=usr_marvel
      - MONGO_INITDB_ROOT_PASSWORD=pwd_marvel
    ports:
      - 27017:27017
    networks:
      - my-network
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  my-network:
    driver: bridge